# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: basic.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'basic.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x62\x61sic.proto\"p\n\x04Root\x12\x17\n\x06header\x18\r \x02(\x0b\x32\x07.Header\x12\x1e\n\ninner_path\x18\x0e \x02(\x0b\x32\n.InnerPath\x12\x16\n\x06\x66ields\x18\x0f \x03(\x0b\x32\x06.Field\x12\x17\n\x06\x66ooter\x18\x10 \x02(\x0b\x32\x07.Footer\"0\n\x06Header\x12\x0f\n\x07project\x18\r \x02(\t\x12\x15\n\x04path\x18\x0e \x02(\x0b\x32\x07.Footer\"m\n\x06\x46ooter\x12*\n\x0c\x64ocumentpath\x18\x01 \x02(\n2\x14.Footer.DocumentPath\x1a\x37\n\x0c\x44ocumentPath\x12\x12\n\ncollection\x18\x02 \x02(\t\x12\x13\n\x0b\x64ocument_id\x18\x04 \x02(\t\"7\n\x0c\x44ocumentPath\x12\x12\n\ncollection\x18\x02 \x02(\t\x12\x13\n\x0b\x64ocument_id\x18\x04 \x02(\t\"4\n\tInnerPath\x12\x10\n\x08segments\x18\x0f \x03(\t\x12\x15\n\rfinal_segment\x18\x11 \x02(\t\"]\n\x05\x46ield\x12\x16\n\x0etype_indicator\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x03 \x02(\t\x12\x17\n\x0f\x61rray_indicator\x18\x04 \x02(\x05\x12\x15\n\x05value\x18\x05 \x02(\x0b\x32\x06.Value\"\x8f\x03\n\x05Value\x12\x17\n\rinteger_value\x18\x01 \x01(\x03H\x00\x12\x17\n\rboolean_value\x18\x02 \x01(\x08H\x00\x12\x15\n\x0b\x62ytes_value\x18\x03 \x01(\x0cH\x00\x12\x16\n\x0c\x64ouble_value\x18\x04 \x01(\x01H\x00\x12\x31\n\x0fgeo_point_value\x18\x05 \x01(\n2\x16.Value.Geo_Point_valueH\x00\x12\x31\n\x0freference_value\x18\x0c \x01(\n2\x16.Value.Reference_valueH\x00\x1a\x36\n\x0fGeo_Point_value\x12\x10\n\x08latitude\x18\x06 \x02(\x01\x12\x11\n\tlongitude\x18\x07 \x02(\x01\x1a~\n\x0fReference_value\x12\x0f\n\x07project\x18\r \x02(\t\x12)\n\x04path\x18\x0e \x02(\n2\x1b.Value.Reference_value.Path\x1a/\n\x04Path\x12\x12\n\ncollection\x18\x0f \x02(\t\x12\x13\n\x0b\x64ocument_id\x18\x11 \x02(\tB\x07\n\x05value\"/\n\x08GeoPoint\x12\x10\n\x08latitude\x18\x06 \x02(\x01\x12\x11\n\tlongitude\x18\x07 \x02(\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'basic_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROOT']._serialized_start=15
  _globals['_ROOT']._serialized_end=127
  _globals['_HEADER']._serialized_start=129
  _globals['_HEADER']._serialized_end=177
  _globals['_FOOTER']._serialized_start=179
  _globals['_FOOTER']._serialized_end=288
  _globals['_FOOTER_DOCUMENTPATH']._serialized_start=233
  _globals['_FOOTER_DOCUMENTPATH']._serialized_end=288
  _globals['_DOCUMENTPATH']._serialized_start=233
  _globals['_DOCUMENTPATH']._serialized_end=288
  _globals['_INNERPATH']._serialized_start=347
  _globals['_INNERPATH']._serialized_end=399
  _globals['_FIELD']._serialized_start=401
  _globals['_FIELD']._serialized_end=494
  _globals['_VALUE']._serialized_start=497
  _globals['_VALUE']._serialized_end=896
  _globals['_VALUE_GEO_POINT_VALUE']._serialized_start=705
  _globals['_VALUE_GEO_POINT_VALUE']._serialized_end=759
  _globals['_VALUE_REFERENCE_VALUE']._serialized_start=761
  _globals['_VALUE_REFERENCE_VALUE']._serialized_end=887
  _globals['_VALUE_REFERENCE_VALUE_PATH']._serialized_start=840
  _globals['_VALUE_REFERENCE_VALUE_PATH']._serialized_end=887
  _globals['_GEOPOINT']._serialized_start=898
  _globals['_GEOPOINT']._serialized_end=945
# @@protoc_insertion_point(module_scope)
